### ISSUE TITLE
Redundant console.log

### ISSUE THREAD

**Issue by twister55** [Froguard/gulp-ftlmin#1]
Hey! Thanks for this plugin :) 
Can you please remove console.log with options or add a debug flag

**Comment by Froguard** [comment]
@twister55 that`s  a good idea。it is solved in [commit-5cc2b58](https://github.com/Froguard/gulp-ftlmin/commit/5cc2b58a2d40c262a8a482b4ef65080df9981349).
See the version 0.0.3
